### ISSUE TITLE
Failed to launch on Xubuntu 16.04 64-bit

### ISSUE THREAD

**Issue by bjorn** [LucKeyProductions/Quatter#1]
I've eagerly tried installing Quatter through the itch.io app, but it failed to launch. When trying it on the console, I got the following output:
```
bjorn@thinko:~/.config/itch/apps/Quatter$ ./Quatter 
Illegal instruction (core dumped)
```
Possibly interesting output when running in `gdb`:
```
Program received signal SIGILL, Illegal instruction.
0x0000000000af1e00 in kNet::Network::Network() ()
(gdb) bt
#0  0x0000000000af1e00 in kNet::Network::Network() ()
#1  0x00000000008ec6b2 in Urho3D::Network::Network(Urho3D::Context*) ()
#2  0x0000000000450eda in Urho3D::Engine::Engine(Urho3D::Context*) ()
#3  0x00000000004508d5 in Urho3D::Application::Application(Urho3D::Context*) ()
#4  0x00000000004340e9 in MasterControl::MasterControl(Urho3D::Context*) ()
#5  0x0000000000434209 in RunApplication() ()
#6  0x00007ffff6afb830 in __libc_start_main (main=0x40c860 <main>, argc=1, argv=0x7fffffffde18, init=<optimized out>, fini=<optimized out>, rtld_fini=<optimized out>, stack_end=0x7fffffffde08) at ../csu/libc-start.c:291
#7  0x0000000000433939 in _start ()
```

**Comment by Modanung** [comment]
Fixed by building on older machine
